'''
Following import was used as the ssh client did not have X11 forwarding
'''
import matplotlib
matplotlib.use('Agg')


